attributes:
  metadata:
    restrictions:
      - condition: "cluster:net_provider != 'neutron'"
        action: "hide"
        message: This plugin only supports neutron networking
        strict: false
  username:
    value: "admin"
    label: "username"
    description: "Username for Zabbix Administrator"
    weight: 10
    type: "text"
  password:
    value: "zabbix"
    label: "password"
    description: "Password for Zabbix Administrator"
    weight: 20
    type: "password"
  db_password:
    value: "fae2oom_aeR6"
    label: "database password"
    description: "Password for Zabbix Database"
    weight: 30
    type: "password"
  monitoring_password:
    value: "Og1aaQivaiv1"
    label: "monitoring password"
    description: "Password for Monitoring user"
    weight: 30
    type: "password"
